name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: "*"

jobs:

  build:
    name: ${{ matrix.os }} - Go ${{ matrix.go_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      # If you want to matrix build , you can append the following list.
      matrix:
        go_version:
          - 1.13
        os:
          - ubuntu-latest

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        # Cache
        path: ~/go/pkg/mod
        # Cache key
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: |
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        else
            go get -v -t -d ./...
        fi

    - name: golangci-lint
      # You may pin to the exact commit or the version.
      # uses: actions-contrib/golangci-lint@502d94948c3b222dc7f1ce576a25269037600ef9
      uses: actions-contrib/golangci-lint@v1
      with:
        # golangci-lint docker release tag
        golangci_lint_version: 1.32.2 # optional, default is v1.23

    - name: Verify
      run: |
        make verify

    - name: Integrate Test
      run: |
        chmod +x integrate_test.sh && ./integrate_test.sh

    - name: Post Coverage
      run: bash <(curl -s https://codecov.io/bash)
